// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/sentinel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Acknowledgment mode
type ProduceRequest_Acks int32

const (
	ProduceRequest_NONE   ProduceRequest_Acks = 0 // Don't wait for ack (fire and forget)
	ProduceRequest_LEADER ProduceRequest_Acks = 1 // Wait for leader to write
	ProduceRequest_ALL    ProduceRequest_Acks = 2 // Wait for all replicas to write
)

// Enum value maps for ProduceRequest_Acks.
var (
	ProduceRequest_Acks_name = map[int32]string{
		0: "NONE",
		1: "LEADER",
		2: "ALL",
	}
	ProduceRequest_Acks_value = map[string]int32{
		"NONE":   0,
		"LEADER": 1,
		"ALL":    2,
	}
)

func (x ProduceRequest_Acks) Enum() *ProduceRequest_Acks {
	p := new(ProduceRequest_Acks)
	*p = x
	return p
}

func (x ProduceRequest_Acks) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProduceRequest_Acks) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sentinel_proto_enumTypes[0].Descriptor()
}

func (ProduceRequest_Acks) Type() protoreflect.EnumType {
	return &file_proto_sentinel_proto_enumTypes[0]
}

func (x ProduceRequest_Acks) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProduceRequest_Acks.Descriptor instead.
func (ProduceRequest_Acks) EnumDescriptor() ([]byte, []int) {
	return file_proto_sentinel_proto_rawDescGZIP(), []int{1, 0}
}

// Record represents a single message in the log.
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`              // Optional message key for partitioning
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`          // Message payload
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`       // Position in the partition log
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_proto_sentinel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Record) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Record) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Record) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ProduceRequest sends a batch of records to a topic partition.
type ProduceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`          // Topic name
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"` // Partition number
	Records       []*Record              `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`      // Batch of records to append
	Acks          ProduceRequest_Acks    `protobuf:"varint,4,opt,name=acks,proto3,enum=sentinel.ProduceRequest_Acks" json:"acks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	mi := &file_proto_sentinel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_proto_rawDescGZIP(), []int{1}
}

func (x *ProduceRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ProduceRequest) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ProduceRequest) GetAcks() ProduceRequest_Acks {
	if x != nil {
		return x.Acks
	}
	return ProduceRequest_NONE
}

// ProduceResponse confirms records were written.
type ProduceResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BaseOffset int64                  `protobuf:"varint,1,opt,name=base_offset,json=baseOffset,proto3" json:"base_offset,omitempty"` // Offset of first record in batch
	Timestamp  int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                     // Timestamp assigned by broker
	// Error per partition
	Error         *Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_proto_sentinel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_proto_rawDescGZIP(), []int{2}
}

func (x *ProduceResponse) GetBaseOffset() int64 {
	if x != nil {
		return x.BaseOffset
	}
	return 0
}

func (x *ProduceResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProduceResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// ConsumeRequest subscribes to a topic partition starting from an offset.
type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                     // Starting offset (0 = earliest, -1 = latest)
	MaxBytes      int32                  `protobuf:"varint,4,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"` // Max bytes to return per batch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_proto_sentinel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_proto_rawDescGZIP(), []int{3}
}

func (x *ConsumeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumeRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ConsumeRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ConsumeRequest) GetMaxBytes() int32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

// MetadataRequest asks for cluster/topic information.
type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"` // Empty = all topics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_proto_sentinel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_proto_rawDescGZIP(), []int{4}
}

func (x *MetadataRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

// MetadataResponse contains cluster and topic metadata.
type MetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brokers       []*Broker              `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	Topics        []*TopicMetadata       `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	ControllerId  int32                  `protobuf:"varint,3,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_proto_sentinel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_proto_rawDescGZIP(), []int{5}
}

func (x *MetadataResponse) GetBrokers() []*Broker {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *MetadataResponse) GetTopics() []*TopicMetadata {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *MetadataResponse) GetControllerId() int32 {
	if x != nil {
		return x.ControllerId
	}
	return 0
}

// Broker describes a node in the cluster.
type Broker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Broker) Reset() {
	*x = Broker{}
	mi := &file_proto_sentinel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Broker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broker) ProtoMessage() {}

func (x *Broker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broker.ProtoReflect.Descriptor instead.
func (*Broker) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_proto_rawDescGZIP(), []int{6}
}

func (x *Broker) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Broker) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Broker) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// TopicMetadata describes a topic and its partitions.
type TopicMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Partitions    []*PartitionMetadata   `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicMetadata) Reset() {
	*x = TopicMetadata{}
	mi := &file_proto_sentinel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicMetadata) ProtoMessage() {}

func (x *TopicMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicMetadata.ProtoReflect.Descriptor instead.
func (*TopicMetadata) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_proto_rawDescGZIP(), []int{7}
}

func (x *TopicMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicMetadata) GetPartitions() []*PartitionMetadata {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *TopicMetadata) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// PartitionMetadata describes a single partition.
type PartitionMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Leader        int32                  `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`            // Broker ID of leader
	Replicas      []int32                `protobuf:"varint,3,rep,packed,name=replicas,proto3" json:"replicas,omitempty"` // All replica broker IDs
	Isr           []int32                `protobuf:"varint,4,rep,packed,name=isr,proto3" json:"isr,omitempty"`           // In-sync replica broker IDs
	Error         *Error                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionMetadata) Reset() {
	*x = PartitionMetadata{}
	mi := &file_proto_sentinel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionMetadata) ProtoMessage() {}

func (x *PartitionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionMetadata.ProtoReflect.Descriptor instead.
func (*PartitionMetadata) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_proto_rawDescGZIP(), []int{8}
}

func (x *PartitionMetadata) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PartitionMetadata) GetLeader() int32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *PartitionMetadata) GetReplicas() []int32 {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *PartitionMetadata) GetIsr() []int32 {
	if x != nil {
		return x.Isr
	}
	return nil
}

func (x *PartitionMetadata) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Error represents an error code and message.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_sentinel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sentinel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_sentinel_proto_rawDescGZIP(), []int{9}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_sentinel_proto protoreflect.FileDescriptor

const file_proto_sentinel_proto_rawDesc = "" +
	"\n" +
	"\x14proto/sentinel.proto\x12\bsentinel\"f\n" +
	"\x06Record\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xca\x01\n" +
	"\x0eProduceRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12*\n" +
	"\arecords\x18\x03 \x03(\v2\x10.sentinel.RecordR\arecords\x121\n" +
	"\x04acks\x18\x04 \x01(\x0e2\x1d.sentinel.ProduceRequest.AcksR\x04acks\"%\n" +
	"\x04Acks\x12\b\n" +
	"\x04NONE\x10\x00\x12\n" +
	"\n" +
	"\x06LEADER\x10\x01\x12\a\n" +
	"\x03ALL\x10\x02\"w\n" +
	"\x0fProduceResponse\x12\x1f\n" +
	"\vbase_offset\x18\x01 \x01(\x03R\n" +
	"baseOffset\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12%\n" +
	"\x05error\x18\x03 \x01(\v2\x0f.sentinel.ErrorR\x05error\"y\n" +
	"\x0eConsumeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x1b\n" +
	"\tmax_bytes\x18\x04 \x01(\x05R\bmaxBytes\")\n" +
	"\x0fMetadataRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"\x94\x01\n" +
	"\x10MetadataResponse\x12*\n" +
	"\abrokers\x18\x01 \x03(\v2\x10.sentinel.BrokerR\abrokers\x12/\n" +
	"\x06topics\x18\x02 \x03(\v2\x17.sentinel.TopicMetadataR\x06topics\x12#\n" +
	"\rcontroller_id\x18\x03 \x01(\x05R\fcontrollerId\"@\n" +
	"\x06Broker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"\x87\x01\n" +
	"\rTopicMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\n" +
	"partitions\x18\x02 \x03(\v2\x1b.sentinel.PartitionMetadataR\n" +
	"partitions\x12%\n" +
	"\x05error\x18\x03 \x01(\v2\x0f.sentinel.ErrorR\x05error\"\xa3\x01\n" +
	"\x11PartitionMetadata\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12\x16\n" +
	"\x06leader\x18\x02 \x01(\x05R\x06leader\x12\x1a\n" +
	"\breplicas\x18\x03 \x03(\x05R\breplicas\x12\x10\n" +
	"\x03isr\x18\x04 \x03(\x05R\x03isr\x12%\n" +
	"\x05error\x18\x05 \x01(\v2\x0f.sentinel.ErrorR\x05error\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xcb\x01\n" +
	"\bSentinel\x12>\n" +
	"\aProduce\x12\x18.sentinel.ProduceRequest\x1a\x19.sentinel.ProduceResponse\x127\n" +
	"\aConsume\x12\x18.sentinel.ConsumeRequest\x1a\x10.sentinel.Record0\x01\x12F\n" +
	"\rFetchMetadata\x12\x19.sentinel.MetadataRequest\x1a\x1a.sentinel.MetadataResponseB$Z\"github.com/matteso1/sentinel/protob\x06proto3"

var (
	file_proto_sentinel_proto_rawDescOnce sync.Once
	file_proto_sentinel_proto_rawDescData []byte
)

func file_proto_sentinel_proto_rawDescGZIP() []byte {
	file_proto_sentinel_proto_rawDescOnce.Do(func() {
		file_proto_sentinel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sentinel_proto_rawDesc), len(file_proto_sentinel_proto_rawDesc)))
	})
	return file_proto_sentinel_proto_rawDescData
}

var file_proto_sentinel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_sentinel_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_sentinel_proto_goTypes = []any{
	(ProduceRequest_Acks)(0),  // 0: sentinel.ProduceRequest.Acks
	(*Record)(nil),            // 1: sentinel.Record
	(*ProduceRequest)(nil),    // 2: sentinel.ProduceRequest
	(*ProduceResponse)(nil),   // 3: sentinel.ProduceResponse
	(*ConsumeRequest)(nil),    // 4: sentinel.ConsumeRequest
	(*MetadataRequest)(nil),   // 5: sentinel.MetadataRequest
	(*MetadataResponse)(nil),  // 6: sentinel.MetadataResponse
	(*Broker)(nil),            // 7: sentinel.Broker
	(*TopicMetadata)(nil),     // 8: sentinel.TopicMetadata
	(*PartitionMetadata)(nil), // 9: sentinel.PartitionMetadata
	(*Error)(nil),             // 10: sentinel.Error
}
var file_proto_sentinel_proto_depIdxs = []int32{
	1,  // 0: sentinel.ProduceRequest.records:type_name -> sentinel.Record
	0,  // 1: sentinel.ProduceRequest.acks:type_name -> sentinel.ProduceRequest.Acks
	10, // 2: sentinel.ProduceResponse.error:type_name -> sentinel.Error
	7,  // 3: sentinel.MetadataResponse.brokers:type_name -> sentinel.Broker
	8,  // 4: sentinel.MetadataResponse.topics:type_name -> sentinel.TopicMetadata
	9,  // 5: sentinel.TopicMetadata.partitions:type_name -> sentinel.PartitionMetadata
	10, // 6: sentinel.TopicMetadata.error:type_name -> sentinel.Error
	10, // 7: sentinel.PartitionMetadata.error:type_name -> sentinel.Error
	2,  // 8: sentinel.Sentinel.Produce:input_type -> sentinel.ProduceRequest
	4,  // 9: sentinel.Sentinel.Consume:input_type -> sentinel.ConsumeRequest
	5,  // 10: sentinel.Sentinel.FetchMetadata:input_type -> sentinel.MetadataRequest
	3,  // 11: sentinel.Sentinel.Produce:output_type -> sentinel.ProduceResponse
	1,  // 12: sentinel.Sentinel.Consume:output_type -> sentinel.Record
	6,  // 13: sentinel.Sentinel.FetchMetadata:output_type -> sentinel.MetadataResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_sentinel_proto_init() }
func file_proto_sentinel_proto_init() {
	if File_proto_sentinel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sentinel_proto_rawDesc), len(file_proto_sentinel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sentinel_proto_goTypes,
		DependencyIndexes: file_proto_sentinel_proto_depIdxs,
		EnumInfos:         file_proto_sentinel_proto_enumTypes,
		MessageInfos:      file_proto_sentinel_proto_msgTypes,
	}.Build()
	File_proto_sentinel_proto = out.File
	file_proto_sentinel_proto_goTypes = nil
	file_proto_sentinel_proto_depIdxs = nil
}
